# ====== Spring configuration ====== #
server:
  port: 8080

spring:
  application:
    name: zawya-gateway-service
  cloud:
    gateway:
      routes:
        - id: zawyaReferentiel
          uri: http://localhost:8081/
          predicates:
            - Path=/referentiel/**
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"

# ====== Actuator configuration ====== #
management:
  endpoints:
    web:
      exposure:
        include: "*"
