# ====== Spring configuration ====== #
server:
  port: 8080

spring:
  application:
    name: zawya-gateway-service
  cloud:
    gateway:
      routes:
        - id: zawyaReferentiel
          uri: http://localhost:8081/
          predicates:
            - Path=/referentiel/**
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

# ====== Actuator configuration ====== #
management:
  endpoints:
    web:
      exposure:
        include: "*"

# ====== Cors configuration ====== #
logging:
  level:
    ROOT: DEBUG
    reactor:
      netty: DEBUG
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG
